Add method for debugging + minimal refactoring
superwf/vuex-cache pull request #57
Opened 2022-04-27 13:09 UTC by rah-emil

Please, merge this editions

2022-04-27 17:59 UTC, VitorLuizC requested changes
I'll be glad to merge your PR if you undo formatting changes and the replacement of `.toBe(false)` and `.toBe(true)` assertions. We choose `.toBe(false)` assertion because it doesn't considers `0`, `""`, `NaN`, `null` and `undefined` values as valid, and the same applies to `.toBe(true)`.

2022-04-27 17:59 UTC, VitorLuizC commented on README.md
> +import createCache from '../plugins/@rah-emil-vuex-cache';
```suggestion
import createCache from 'vuex-cache';
```

2022-04-28 06:41 UTC, rah-emil commented on README.md
> +import createCache from '../plugins/@rah-emil-vuex-cache';
Came here by accident. Thanks!)

2022-04-28 09:26 UTC, rah-emil commented
I hope everything is fine😊

2022-04-28 12:03 UTC, VitorLuizC approved these changes

2022-04-28 12:04 UTC, merged

2022-04-28 12:54 UTC, VitorLuizC commented
Released under [`v3.5.0`](https://www.npmjs.com/package/vuex-cache/v/3.5.0) version.